name: parking_slot
description:  This is parking mobile application. Where car owner can park their cars in their nearby locations. 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_launcher_name: ^0.0.1

  flutter:
    sdk: flutter

  flutter_launcher_icons: "^0.8.0"

  cupertino_icons: ^1.0.0

  get: ^3.24.0

  dataclass: ^0.5.0

  image_picker: ^0.6.7+22

  flutter_svg: ^0.19.1

  fluttertoast: ^7.1.6

  firebase_core: ^0.7.0
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  firebase_database: ^6.0.0
  firebase_messaging: ^6.0.16

  progress_dialog: ^1.2.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  dataclass_generator: ^0.5.0



flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Bank Gothic
      fonts:
        - asset: assets/fonts/bank_gothic.ttf
